### ISSUE TITLE
Unsupported extension (DerivingStrategies) crashes brittany

### ISSUE THREAD

**Issue by lspitzner** [lspitzner/brittany#156]
just noticed that the webservice backend crashed with "Unsupported extension: DerivingStrategies". Cannot reproduce with brittany executable, although the backend uses brittany as a library and my local executable is compiled using a newer ghc (iirc). Probably needs ghc-8.0 to reproduce. Even so, ghc will only get more extensions in the future so we should prevent this kind of crash. should be one `catch` in the right spot.

**Comment by tfausak** [comment]
I think this is fixed now? Using https://hexagoxel.de/brittany/ I can enable `DerivingStrategies` without causing a crash. However attempting to actually _use_ deriving strategies does crash. I'm not sure if this issue was for gracefully handling unknown extensions or handling deriving strategies specifically. 

``` hs
-- succeeds
{-# langugae DerivingStrategies #-}
data T deriving Eq
```

``` hs
-- fails
{-# langugae DerivingStrategies #-}
data T deriving stock Eq
```

**Comment by lspitzner** [comment]
Yeah I see it is not reproducable. It probably depends on the version of ghc the backend was compiled with. And perhaps it is fixed on ghc's end in later versions anyway. But I want to investigate this a bit more, I should still have the server logs somewhere. Keep it open for the moment.

**Comment by tfausak** [comment]
👍 

For what it's worth, even the `deriving stock` thing works with the current HEAD (b2d8a1ed51b88894d336707580e4aa2ba0aaab33). So it seems like this is indeed associated with the GHC version.
