### ISSUE TITLE
Aditional configuration request

### ISSUE THREAD

**Issue by alx741** [lspitzner/brittany#7]
I'm trying out *brittany* and really like it, I think it has the potential to beat *hindent* through configuration capabilities; The latest *hindent* version completely removes the styles mechanism and is fixed to the "Johan Tibell" one with no more configuration other than indentation size and line length, Johan Tibell's style is pretty good but I'm not always necessarily happy with every way it changes the code.

As I try *brittany* I found out a couple things that bothers me and that I would like to be able to configure on `~/.brittany/config.yaml`. Not to say that the default behavior is bad though:

### Guards
Have/Want:
```Haskell
isValidPosition :: Position -> Maybe Position
isValidPosition position
    | validX && validY = Just position
    | otherwise = Nothing
```
Get:
```Haskell
isValidPosition :: Position -> Maybe Position
isValidPosition position
    | validX && validY
    = Just position
    | otherwise
    = Nothing
```

### Case
Have/Want:
```Haskell
dropTile :: Board -> Position -> Board
dropTile board position =
    case cell of
        Just (Tile _) -> board'
        _ -> board
```
Get:
```Haskell
dropTile :: Board -> Position -> Board
dropTile board position = case cell of
    Just (Tile _) -> board'
    _ -> board
```

**Comment by lspitzner** [comment]
Sorry for the slow reply, I struggle to find time to work more on brittany. You are totally right about the incomplete Guard layouting, there simply is one case missing from the corresponding translation ruleset. I have run into this exact problem as well, so there is a good chance that I will fix it relatively soon :p

For the `case` part, I am not sure what exactly you want. The implementation currently roughly works like this: Certain syntactical constructs are translated to a (first line, indented-rest-of-lines-list) thingy.
Examples for applications of this rule include:

~~~~.hs
foo = case cell of
  ..
foo = do
  ..
foo $ do
  ..
foo $ if expr
  then ..
  else ..
foo $ case abc of
  ..
foo $ bar
  { ..
  }
~~~~

And while it certainly is possible to disable this, before I implement this I would like to confirm in what instances you actually want this. just for `case` and after `=` of a binding?

**Comment by lspitzner** [comment]
(Note to self: maybe the desired effect is just replacing docForceParSpacing with docForceSingleLine [in this line](https://github.com/lspitzner/brittany/blob/508780466c68a94aead96b58ad9f68c4da430cee/src/Language/Haskell/Brittany/Layouters/Decl.hs#L249))

**Comment by lspitzner** [comment]
The "guards" part of this issue should be resolved with that commit.

**Comment by alx741** [comment]
Great, But I'm not sure what the `config.yaml` option is to configure that behavior (?)

There is a problem though, it gives an error:

```
error reading in brittany config from /home/alx/.brittany/config.yaml:
Error in $: key "conf_debug" not present
```

I've already tried removing the old `~/.brittany/config.yaml` and let brittany re-generate it, but the problem persists

**Comment by lspitzner** [comment]
I can reproduce..  that must have been broken since some commits. One sec.

**Comment by lspitzner** [comment]
fix is pushed.

**Comment by lspitzner** [comment]
The behaviour for guards is improved "unconditionally", i.e. not behind some config flag. Like in other cases, the layouting changes depending on available space. See [the testcases for the new behaviour](https://github.com/lspitzner/brittany/blob/cea81d53690e6c0afe3bda92a2d1805e9de707be/src-literatetests/tests.blt#L454-L468).

**Comment by lspitzner** [comment]
(oh, and looking at the testcases, I notice that one is missing. And it really did not work, fix is pushed. But you prob. won't run into that unless you have multiple, long guards.)

**Comment by alx741** [comment]
Perfect, now it works nicely, thanks!

**Comment by lspitzner** [comment]
closing due to no feedback on the "case" part of the initial description; feel free to open again if desired.
